dataset:
  train_path: ./data/train
  test_path: ./data/test

log_dir: ./logs

preprocess:
  crop_height: 90
  crop_width: 90

model:
  num_classes: 39

train:
  batch_size: 4
  num_epochs: 20
  learning_rate: !!float 1e-4
