dataset:
  train_path: ./data/train
  test_path: ./data/test

preprocess:
  timesteps: 45
  crop_height: 112
  crop_width: 112
  sample_rate: 2

model:
  num_classes: 39

train:
  log_dir: ./logs
  train_ratio: 0.9
  batch_size: 16
  num_epochs: 40
  learning_rate: !!float 3e-5

infer:
  batch_size: 8
  dir: ./logs/20221020-142656
