dataset:
  train_path: ./data/train
  test_path: ./data/test

preprocess:
  crop_height: 90
  crop_width: 90

model:
  num_classes: 39

train:
  log_dir: ./logs
  batch_size: 4
  num_epochs: 40
  learning_rate: !!float 1e-4

infer:
  batch_size: 4
  dir: ./logs/
