train:
  batch_size: 16
  update_batch_size: 1024
  epochs: 1000
  save_freq: 200

  lr: !!float 1e-4
  weight_decay: !!float 1e-6

model:
  encoder:
    # One of ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152']
    name: resnet50
    latent_dim: 512
  projector:
    dims: [256, 128]
